### ISSUE TITLE
Add `typos` pre-commit hook

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/faim-ipa#131]
Seems to be useful, and with a low false-positive rate, shouldn't be too annoying.

```
  - repo: https://github.com/crate-ci/typos
    rev: v1.20.7
    hooks:
      - id: typos
        files: \.(py|md|rst|yaml|toml)
        # empty to do not write fixes
        args: []
        exclude: pyproject.toml
```
